######################################################################
# Automatically generated by qmake (2.01a) Thu Nov 11 18:56:58 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h popup.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp popup.cpp
